### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by invexx** [xueyuanl/cambrinary#1]
Traceback (most recent call last):
  File "cambrinary.py", line 6, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by xueyuanl** [comment]
Because your python environment miss BeautifulSoup package.
In the project dir, try:
`pip2 install -r requirements.txt`

**Comment by invexx** [comment]
Thank you. Works perfectly now.
