### ISSUE TITLE
Getting empty string using -t option

### ISSUE THREAD

**Issue by nevfy-y** [xueyuanl/cambrinary#13]
For example: `cambrinary -w dog -t russian` prints just one empty string, but `cambrinary -w dog -t japanese` works fine. It would be nice to get some error message instead of the empty string in this case. Is it possible that there is no Russian explanation for most words? Russian is displayed properly in other terminal applications, so this should not be a problem with that I guess?..

**Comment by xueyuanl** [comment]
thanks for your issue fixed in #14
