### ISSUE TITLE
Please support Python3

### ISSUE THREAD

**Issue by jarun** [xueyuanl/cambrinary#2]
I came across your post on Reddit and this is extremely useful while teaching my kid. I was too reluctant to start a new project myself but I've always missed this!

I would be great if you could add Python3 support (please refer to [googler](https://github.com/jarun/googler) or [Buku](https://github.com/jarun/Buku) for HTTP query-response examples.

**Comment by xueyuanl** [comment]
The project has been migrated to python3. Hope your kid would enjoy it! And thank you for the reference, I would study it and amend the code shortly.

**Comment by jarun** [comment]
Thank you so much!
