### ISSUE TITLE
[Request] Add Turkish Lang.

### ISSUE THREAD

**Issue by toprak** [xueyuanl/cambrinary#4]
I hope you could add Turkish Lang.
Thanks

**Comment by toprak** [comment]
I did learn english instead of waiting for this :D

**Comment by xueyuanl** [comment]
> I did learn english instead of waiting for this :D

So sorry for this firstly, it may made you disappoint, it's really a so long time that people and thing changed so much. And I thought you already forgot about this issue. Support and maintain a not so popular language need more extra time and energy (cambridge website use different html tag in different language), 
so I haven't paid attention to it all this time.

But yes, what I want to say is, you made a good choice. using English to learn and understand English word is the best way to study. This is why I decided not translate the example sentence and just give the translation of the difinition of the word. Actually, I hope people use cambrinary with no `-t` option, just using English to learn English.

Thanks for your usage and suggestion, and have a nice day : )
