### ISSUE TITLE
Doesn't show definitions.

### ISSUE THREAD

**Issue by cartals** [xueyuanl/cambrinary#5]
I typed line like your example but terminal doesn't show definitions.
https://imgur.com/gallery/V7qZG2C

**Comment by xueyuanl** [comment]
yes, the cambridge change the html tags, I will fix it soon.

**Comment by xueyuanl** [comment]
Hi cartals, I have updated the code, please confirm it.
`pip3 install --upgrade cambrinary` or just pull and `pip3 install .` locally.

**Comment by cartals** [comment]
It works great thanks.
